### ISSUE TITLE
师哥真的是0基础Python➕GPT写出来的吗，看起来不太像啊。

### ISSUE THREAD

**Issue by d1swen** [sakurasep/qfnuLibraryBook#1]
提词思路是什么
By the way，师哥你的博客403我了😭我还没点开过就403了

**Comment by sakurasep** [comment]
> 提词思路是什么 By the way，师哥你的博客403我了😭我还没点开过就403了

方便加一下 TG 吗，我这个博客不知道咋回事经常会 403

**Comment by sakurasep** [comment]
确实没学过 Python，边问 chatgpt 边学，Python 确实简单
<img width="226" alt="image" src="https://github.com/sakurasep/qfnuLibraryBook/assets/70024132/d882e374-6b56-48cd-93f7-e6cecf1906b1">
<img width="237" alt="image" src="https://github.com/sakurasep/qfnuLibraryBook/assets/70024132/429bdef0-8580-480d-83b4-e4b0780fd193">
<img width="222" alt="image" src="https://github.com/sakurasep/qfnuLibraryBook/assets/70024132/90211c8d-3f36-481f-b838-e486708c4e26">

**Comment by W1ndys** [comment]
> 方便加一下 TG 吗，我这个博客不知道咋回事经常会 403

已加（但是不怎么经常看）

> 确实没学过 Python，边问 chatgpt 边学，Python 确实简单

多少有基础（狗头）
给师弟了一点小小的震撼🫡🫡🫡
学习一下

**Comment by d1swen** [comment]
> 方便加一下 TG 吗，我这个博客不知道咋回事经常会 403

已加（但是不怎么经常看）

> 确实没学过 Python，边问 chatgpt 边学，Python 确实简单

多少有基础（狗头）
给师弟了一点小小的震撼🫡🫡🫡
学习一下

**Comment by d1swen** [comment]
> By the way，师哥你的博客403我了😭我还没点开过就403了

最新消息
blog已正常
但主页还在403

**Comment by sakurasep** [comment]
> > By the way，师哥你的博客403我了😭我还没点开过就403了
> 
> 最新消息
> blog已正常
> 但主页还在403

估计是cdn的问题，我是cos套cdn。目前确实没有啥好办法加速网站在国内的访问。挂梯子访问 [Vercel托管](https://hexo.sakurasep.site)是最快的
