### ISSUE TITLE
到19:20预约的时候反馈预约时间过长，程序自动停止

### ISSUE THREAD

**Issue by erkangkang** [sakurasep/qfnuLibraryBook#2]
师哥你好，今天在使用2.3版本的时候，到19：20运行程序后产生以下报错
INFO:__main__:距离预约时间过长，程序将自动停止。
以下是我配置文件的内容，其余代码未作修改
这是我配置文件的内容

```python
# Telegram 相关
#CHANNEL_ID: ""
#TELEGRAM_BOT_TOKEN: ""

# #Bark 相关
#BARK_URL: ""
#BARK_EXTRA: "?icon=https://cdn.sakurasep.site/Website/new_avatar_256.png"

# Anpush 相
ANPUSH_TOKEN: "*****"
ANPUSH_CHANNEL: "***"

# 账号授权相关
USERNAME: "*****"
PASSWORD: "******"

# 是否是 Github Action
GITHUB: True

# 程序设置
MODE: "1"
SEAT_ID:
  - 7520
  - 7543
DATE: "tomorrow"
CLASSROOMS_NAME:
  - 西校区图书馆-五层自习室
  - 西校区图书馆-四层自习室
  - 西校区图书馆-三层自习室
```

**Comment by erkangkang** [comment]
这是我配置文件的内容
# Telegram 相关
#CHANNEL_ID: ""
#TELEGRAM_BOT_TOKEN: ""

# Bark 相关
#BARK_URL: ""
#BARK_EXTRA: "?icon=https://cdn.sakurasep.site/Website/new_avatar_256.png"

# Anpush 相关
ANPUSH_TOKEN: "*****"
ANPUSH_CHANNEL: "***"

# 账号授权相关
USERNAME: "*****"
PASSWORD: "******"

# 是否是 Github Action
GITHUB: True

# 程序设置
MODE: "1"
SEAT_ID:
  - 7520
  - 7543
DATE: "tomorrow"
CLASSROOMS_NAME:
  - 西校区图书馆-五层自习室
  - 西校区图书馆-四层自习室
  - 西校区图书馆-三层自习室

**Comment by erkangkang** [comment]
刚才重新测试了一下，将配置文件中的是否是 Github Action设置为false即可正常使用，大概是时间判定是出了问题

**Comment by sakurasep** [comment]
Github Action使用的是UTC时间，如果你不是在Github上运行，这一点要改为false

**Comment by sakurasep** [comment]
> 刚才重新测试了一下，将配置文件中的是否是 Github Action设置为false即可正常使用，大概是时间判定是出了问题

看你是本地运行，希望遇到卡死或者死循环的情况，请及时告知我，我会针对进行修复

**Comment by erkangkang** [comment]
我在服务器上部署了最新版本，并且设置了19:20定时任务，但是昨天预约时报错获取座位信息失败



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月25日(周一) 上午8:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sakurasep/qfnuLibraryBook] 到19:20预约的时候反馈预约时间过长，程序自动停止 (Issue #2)




  
刚才重新测试了一下，将配置文件中的是否是 Github Action设置为false即可正常使用，大概是时间判定是出了问题
  
看你是本地运行，希望遇到卡死或者死循环的情况，请及时告知我，我会针对进行修复

**Comment by sakurasep** [comment]
> 我在服务器上部署了最新版本，并且设置了19:20定时任务，但是昨天预约时报错获取座位信息失败
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月25日(周一) 上午8:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [sakurasep/qfnuLibraryBook] 到19:20预约的时候反馈预约时间过长，程序自动停止 (Issue #2) 刚才重新测试了一下，将配置文件中的是否是 Github Action设置为false即可正常使用，大概是时间判定是出了问题 看你是本地运行，希望遇到卡死或者死循环的情况，请及时告知我，我会针对进行修复 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

有没有详细的 log，因为晚上是服务器压力较大的时间，很难去查是哪一环节出了问题

**Comment by sakurasep** [comment]
还有就是，Release 版本是阶段性测试没问题后发布的版本，最近有朋友帮我测出来一些 bug，这些 bug 的修复都优先推送到仓库，Release 并不一定会更新，如果可以的话请在服务器使用 git 直接 clone仓库，当出现 bug 的时候可以尝试 pull 拉取最新修改。

**Comment by erkangkang** [comment]
感谢师哥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月25日(周一) 上午9:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sakurasep/qfnuLibraryBook] 到19:20预约的时候反馈预约时间过长，程序自动停止 (Issue #2)




 
还有就是，Release 版本是阶段性测试没问题后发布的版本，最近有朋友帮我测出来一些 bug，这些 bug 的修复都优先推送到仓库，Release 并不一定会更新，如果可以的话请在服务器使用 git 直接 clone仓库，当出现 bug 的时候可以尝试 pull 拉取最新修改。
